feat: removed project specifics

diff --git a/git/javascript/hooks/pre-commit b/git/javascript/hooks/pre-commit
--- a/git/javascript/hooks/pre-commit
+++ b/git/javascript/hooks/pre-commit
@@ -6,39 +6,32 @@ echo "╚═══════════════════════�
 
 set -e
 
-staged_files=$(git diff --cached --name-only --diff-filter=ACM -- 'module/**/*')
-
-cd ./module
+staged_files=$(git diff --cached --name-only --diff-filter=ACM -- 'src/**/*')
 
 if [ -n "$staged_files" ]; then
-    # remove module as it is the root of the typecript project
-    staged_module_files=$(echo "$staged_files" | sed 's|^module/||')
+    npx prettier --loglevel warn --write $staged_files
+    git add $staged_module_files
 
-    if [ -n "$staged_module_files" ]; then
-        npx prettier --loglevel warn --write $staged_module_files
-        git add $staged_module_files
+    js_ts_files=$(echo "$staged_files" | grep -E '\.(js|jsx|ts|tsx)$' || true)
+    if [ -n "$js_ts_files" ]; then
+        npx eslint --quiet $js_ts_files || (echo "ERROR ESLint failed" && exit 1)
+    fi
 
-        js_ts_files=$(echo "$staged_module_files" | grep -E '\.(js|jsx|ts|tsx)$' || true)
-        if [ -n "$js_ts_files" ]; then
-            npx eslint --quiet $js_ts_files || (echo "ERROR ESLint failed" && exit 1)
-        fi
+    scss_css_files=$(echo "$staged_files" | grep -E '\.(scss|css)$' || true)
+    if [ -n "$scss_css_files" ]; then
+        npx stylelint --quiet $scss_css_files || (echo "ERROR Stylelint failed" && exit 1)
+    fi
 
-        scss_css_files=$(echo "$staged_module_files" | grep -E '\.(scss|css)$' || true)
-        if [ -n "$scss_css_files" ]; then
-            npx stylelint --quiet $scss_css_files || (echo "ERROR Stylelint failed" && exit 1)
-        fi
-
-        if [ -n "$js_ts_files" ]; then
-            for file in $js_ts_files; do
-                dir=$(dirname "$file")
-                filename=$(basename "$file")
-                extension="${filename##*.}"
-                filename="${filename%.*}"
-                test_file="$dir/__tests__/$filename.test.$extension"
-                if [ -e "$test_file" ]; then
-                    npm run test $test_file || (echo "ERROR: Tests failed" && exit 1)
-                fi
-            done
-        fi
+    if [ -n "$js_ts_files" ]; then
+        for file in $js_ts_files; do
+            dir=$(dirname "$file")
+            filename=$(basename "$file")
+            extension="${filename##*.}"
+            filename="${filename%.*}"
+            test_file="$dir/__tests__/$filename.test.$extension"
+            if [ -e "$test_file" ]; then
+                npm run test $test_file || (echo "ERROR: Tests failed" && exit 1)
+            fi
+        done
     fi
 fi
